import Link from "next/link";
import { ArrowRight, BarChart3, BookOpen, Check, GraduationCap, ShieldCheck, Users } from "lucide-react";
import { ProductPreview } from "../components/ProductPreview";
import { SectionHeading } from "../components/SectionHeading";

export default function Home(){return <main>
 <section className="hero"><div className="hero-glow"/><div className="container hero-grid"><div className="hero-copy"><span className="eyebrow light">SOFTWARE FOR MODERN ORGANIZATIONS</span><h1>Software that makes <span>organizations smarter.</span></h1><p>Stanfordos builds practical, connected software that simplifies complex operations and gives teams a clearer way to work.</p><div className="hero-actions"><Link href="/products/school-management" className="button primary">Explore Products <ArrowRight size={18}/></Link><Link href="/book-demo" className="button ghost">Book a Demo</Link></div><div className="hero-trust"><span className="trust-badge">S</span><span className="trust-badge">T</span><span className="trust-badge">A</span><span>Built for teams that want less complexity.</span></div></div><ProductPreview/></div></section>
 <section className="stats"><div className="container stat-grid"><Stat value="1" label="Core product today"/><Stat value="30+" label="Operational capabilities"/><Stat value="24/7" label="Access to your platform"/><Stat value="1" label="Connected experience"/></div></section>
 <section className="section"><div className="container"><SectionHeading eyebrow="OUR PRODUCT" title="One platform for the work that matters" text="Our flagship school management platform brings everyday administration, academics and finance into one connected experience."/><div className="product-card"><div className="product-card-copy"><span className="product-kicker">SCHOOL MANAGEMENT SYSTEM</span><h3>Run your entire school from one calm, connected dashboard.</h3><p>Give administrators, teachers and school leaders one place to manage the work that keeps a school moving.</p><div className="feature-list"><span><Check/> Student management</span><span><Check/> Attendance & academics</span><span><Check/> Fees & finance</span><span><Check/> Reports & analytics</span></div><Link href="/products/school-management" className="text-link">Explore the platform <ArrowRight size={17}/></Link></div><div className="product-card-image"><ProductPreview/></div></div></div></section>
 <section className="section muted" id="solutions"><div className="container"><SectionHeading eyebrow="DESIGNED AROUND PEOPLE" title="A better experience for every role" text="The platform is built to reduce friction across the school ecosystem." center/><div className="solution-grid"><Solution icon={<GraduationCap/>} title="School leaders" text="Get visibility across operations, performance and finances."/><Solution icon={<Users/>} title="Teachers" text="Spend less time on administration and more time teaching."/><Solution icon={<BookOpen/>} title="Students & parents" text="Make communication, records and school information easier to access."/></div></div></section>
 <section className="section"><div className="container feature-band"><div><span className="eyebrow">BUILT FOR CLARITY</span><h2>Less switching. More doing.</h2><p>Stanfordos brings the essential pieces of school operations together so your team can work from one source of truth.</p></div><div className="mini-features"><Mini icon={<BarChart3/>} title="Clear insights"/><Mini icon={<ShieldCheck/>} title="Secure by design"/><Mini icon={<Users/>} title="Role-based access"/></div></div></section>
 <section className="cta"><div className="container cta-inner"><span className="eyebrow light">SEE STANFORDOS IN ACTION</span><h2>Ready to see what a connected school can look like?</h2><p>Book a personalized demo with our team.</p><Link href="/book-demo" className="button white">Book a Demo <ArrowRight size={18}/></Link></div></section>
 </main>}
function Stat({value,label}:{value:string;label:string}){return <div className="stat"><strong>{value}</strong><span>{label}</span></div>}
function Solution({icon,title,text}:{icon:React.ReactNode;title:string;text:string}){return <div className="solution-card"><div className="icon-box">{icon}</div><h3>{title}</h3><p>{text}</p></div>}
function Mini({icon,title}:{icon:React.ReactNode;title:string}){return <div className="mini"><span className="icon-box small">{icon}</span><span>{title}</span></div>}
